Made the version constraint error message more clear
Previously:

    The constraint, 1.6.6, is not consistent with the requirement, 'Django>=1.7'.
    While:
      Updating django.
    Error: Bad constraint 1.6.6 Django>=1.7

Now:

    While:
      Installing django.
    Error: The requirement ('Django>=1.7') is not allowed by your [versions] constraint (1.6.6)

The original message said "bad constraint". No, the constraint is not
necessarily bad. It only conflicts with some other package's requirement.

The new message tells you that "constraint" means "your own [versions]
list".