gha scripts: install setuptools<80.
Otherwise they [fail](https://github.com/buildout/buildout/actions/runs/15045547453/job/42289099422?pr=711):

```
Run sandbox/bin/buildout -v -c .github/workflows/scripts-${PYTHON_VERSION}.cfg annotate buildout
Requires-Python support missing and could not be patched into zc.buildout.

Traceback (most recent call last):
  File "/home/runner/work/buildout/buildout/src/zc/buildout/patches.py", line 60, in patch_PackageIndex
    from setuptools.package_index import PackageIndex
ModuleNotFoundError: No module named 'setuptools.package_index'
Traceback (most recent call last):
  File "/home/runner/work/buildout/buildout/sandbox/bin/buildout", line 5, in <module>
    from zc.buildout.buildout import main
  File "/home/runner/work/buildout/buildout/src/zc/buildout/buildout.py", line 23, in <module>
    import zc.buildout.easy_install
  File "/home/runner/work/buildout/buildout/src/zc/buildout/easy_install.py", line 35, in <module>
    import setuptools.package_index
ModuleNotFoundError: No module named 'setuptools.package_index'
```

See also https://github.com/buildout/buildout/issues/710
Note that we have daily tests for the scripts using setuptools HEAD, and they fail since two weeks:
https://github.com/buildout/buildout/actions/runs/14810993203

This commit does not influence that.