Fix patch_interpret_distro_name to work when patch_PackageIndex failed to run.
Calling `patch_PackageIndex()` might fail due to changes in pip/setuptools.  You can try out this situation by commenting out the `patch_PackageIndex()` call.

Then you get an error when running buildout:

```
Traceback (most recent call last):
  File "/Users/maurits/community/buildout/dev.py", line 27, in <module>
    import zc.buildout.easy_install
  File "/Users/maurits/community/buildout/src/zc/buildout/__init__.py", line 38, in <module>
    import zc.buildout.patches  # NOQA
  File "/Users/maurits/community/buildout/src/zc/buildout/patches.py", line 263, in <module>
    patch_interpret_distro_name()
  File "/Users/maurits/community/buildout/src/zc/buildout/patches.py", line 260, in patch_interpret_distro_name
    setuptools.package_index.interpret_distro_name = interpret_distro_name
AttributeError: module 'setuptools' has no attribute 'package_index'. Did you mean: 'PackageFinder'?
```