TEMPORARY: restrict to running only Windows tests.
The Windows test fails:
https://github.com/buildout/buildout/actions/runs/25044903767/job/73360031112?pr=743

```
Error: There is a version conflict.
We already have: setuptools 82.0.1
but zc.buildout 5.1.4.dev0 requires 'setuptools<82,>=61.0.0'.
```

which is strange, because a few lines up it says it has setuptools 75:

```
pip freeze output:
build==1.4.4
colorama==0.4.6
packaging==26.2
pip==26.1
pyproject_hooks==1.2.0
setuptools==75.8.2
tomli==2.4.1
wheel==0.47.0
```