Drop support for Python 3.8.  Require Python 3.9 as minimum.
The latest test run with setuptools 75.6.0 [fails](https://github.com/buildout/buildout/actions/runs/12206355882/job/34056007822?pr=671#step:5:35) at installing setuptools:

```
ERROR: Ignored the following versions that require a different python version:
75.4.0 Requires-Python >=3.9; 75.5.0 Requires-Python >=3.9; 75.6.0 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement setuptools==75.6.0
```