Removed type hints from the WorkingSet.find patch.
They fail on Python 3.9.  Which is strange, because the latest setuptools version supports Python 3.9, so why does it not fail there?

See [this test run](https://github.com/buildout/buildout/actions/runs/13680729029/job/38252752156?pr=684#step:5:210):

```
Now calling 'python dev.py' to create 'bin/buildout' script in main directory.
Traceback (most recent call last):
  File "/home/runner/work/buildout/buildout/dev.py", line 27, in <module>
    import zc.buildout.easy_install
  File "/home/runner/work/buildout/buildout/src/zc/buildout/__init__.py", line 38, in <module>
    import zc.buildout.patches  # NOQA
  File "/home/runner/work/buildout/buildout/src/zc/buildout/patches.py", line 386, in <module>
    patch_pkg_resources_working_set_find()
  File "/home/runner/work/buildout/buildout/src/zc/buildout/patches.py", line 354, in patch_pkg_resources_working_set_find
    def find(self, req: Requirement) -> Distribution | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```