dev.py: if upgrade of pip fails, try to install it.
One CircleCI build failed with:

```
ImportError: cannot import name 'html5lib' from 'pip._vendor'
```