Windows: import get_win_launcher instead of getting it as attribute.
That is what I actually intended.
The previous way works with latest setuptools, [see Plone coredev run](https://github.com/plone/buildout.coredev/actions/runs/15587534510/job/43897613622?pr=1025), but fails on setuptools 75 in our own tests:

```
Now calling 'python dev.py' to create 'bin/buildout' script in main directory.
Traceback (most recent call last):
  File "C:\a\buildout\buildout\dev.py", line 27, in <module>
    import zc.buildout.easy_install
  File "c:\a\buildout\buildout\src\zc\buildout\easy_install.py", line 268, in <module>
    get_win_launcher = setuptools._scripts.get_win_launcher
AttributeError: module 'setuptools' has no attribute '_scripts'
```