Stop testing with pip 20.
It fails making an editable install because pip passing `--home` which is not accepted by setuptools:

```
bin/buildout || bin/buildout.exe
Creating directory '/Users/maurits/community/buildout/eggs/v5/cp310'.
Creating directory '/Users/maurits/community/buildout/parts'.
Creating directory '/Users/maurits/community/buildout/develop-eggs'.
Develop: '/Users/maurits/community/buildout/zc.recipe.egg_'
Failed to run command:
'/Users/maurits/community/buildout/venvs/python3.10/bin/python3.10', '-m', 'pip', 'install', '--no-deps', '-t', '/Users/maurits/community/buildout/develop-eggs/tmpwfh2t7a8build', '-q', '-e', '/Users/maurits/community/buildout/zc.recipe.egg_'
Error output follows:
    ERROR: Command errored out with exit status 1:
     command: /Users/maurits/community/buildout/venvs/python3.10/bin/python3.10 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/maurits/community/buildout/zc.recipe.egg_/setup.py'"'"'; __file__='"'"'/Users/maurits/community/buildout/zc.recipe.egg_/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --home /private/var/folders/df/k8nj3ds51g1f705y5h9jd_vm0000gn/T/pip-target-dlzjf8qu
         cwd: /Users/maurits/community/buildout/zc.recipe.egg_/
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: option --home not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/maurits/community/buildout/venvs/python3.10/bin/python3.10 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/maurits/community/buildout/zc.recipe.egg_/setup.py'"'"'; __file__='"'"'/Users/maurits/community/buildout/zc.recipe.egg_/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --home /private/var/folders/df/k8nj3ds51g1f705y5h9jd_vm0000gn/T/pip-target-dlzjf8qu Check the logs for full command output.

While:
  Installing.
  Processing develop directory '/Users/maurits/community/buildout/zc.recipe.egg_'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/maurits/community/buildout/src/zc/buildout/buildout.py", line 2351, in main
    getattr(buildout, command)(args)
  File "/Users/maurits/community/buildout/src/zc/buildout/buildout.py", line 748, in install
    installed_develop_eggs = self._develop()
  File "/Users/maurits/community/buildout/src/zc/buildout/buildout.py", line 995, in _develop
    zc.buildout.easy_install.develop(setup, dest)
  File "/Users/maurits/community/buildout/src/zc/buildout/easy_install.py", line 1313, in develop
    egg_name = call_pip_install(directory, tmp3, editable=True)
  File "/Users/maurits/community/buildout/src/zc/buildout/easy_install.py", line 1918, in call_pip_install
    output = get_subprocess_output(list(args), env=env)
  File "/Users/maurits/community/buildout/src/zc/buildout/easy_install.py", line 295, in get_subprocess_output
    raise Exception(msg)
Exception: Failed to run command:
'/Users/maurits/community/buildout/venvs/python3.10/bin/python3.10', '-m', 'pip', 'install', '--no-deps', '-t', '/Users/maurits/community/buildout/develop-eggs/tmpwfh2t7a8build', '-q', '-e', '/Users/maurits/community/buildout/zc.recipe.egg_'
```

pip 21 and higher apparently do this in a different way.  There the tests pass with the same combination of setuptools versions.