Remove some broken tests from custom.rst
Add note in custom.rst that these tests are broken since setuptools 49.6.0.
Basically, the custom egg in the develop-eggs directory is not recognised as an egg, because it has no EGG-INFO directory.

Sample test failure:

```
File "/Users/maurits/community/buildout/zc.recipe.egg_/src/zc/recipe/egg/custom.rst", line 204, in custom.rst
Failed example:
    print_(system(buildout), end='')
Expected:
    Develop: '/sample-buildout/demo'
    Updating extdemo.
    Installing demo.
    Generated script '/sample-buildout/bin/demo'...
Got:
    Develop: '/sample-buildout/demo'
    Updating extdemo.
    Installing demo.
    Getting distribution for 'extdemo'.
    Couldn't find index page for 'extdemo' (maybe misspelled?)
    While:
      Installing demo.
      Getting distribution for 'extdemo'.
    Error: Couldn't find a distribution for 'extdemo'.
```