Require setuptools 61.0.0 as minimum version.
`setuptools` 61 has changes in the auto discovery of package that we now rely on in our tests.
Older versions give errors in our tests due to the new way in which we create the `recipes` test package, using a src-layout instead of specifying `py_modules`:

```
Develop: '/private/var/folders/df/k8nj3ds51g1f705y5h9jd_vm0000gn/T/tmpa253pvqtbuildoutSetUp/_TEST_/sample-buildout/recipes'
While:
  Installing.
  Getting section data-dir.
  Initializing section data-dir.
  Loading zc.buildout recipe entry recipes:mkdir.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Users/maurits/community/buildout/src/zc/buildout/buildout.py", line 2330, in main
    getattr(buildout, command)(args)
  File "/Users/maurits/community/buildout/src/zc/buildout/buildout.py", line 753, in install
    [self[part]['recipe'] for part in install_parts]
  File "/Users/maurits/community/buildout/src/zc/buildout/buildout.py", line 753, in <listcomp>
    [self[part]['recipe'] for part in install_parts]
  File "/Users/maurits/community/buildout/src/zc/buildout/buildout.py", line 1406, in __getitem__
    options._initialize()
  File "/Users/maurits/community/buildout/src/zc/buildout/buildout.py", line 1518, in _initialize
    self.initialize()
  File "/Users/maurits/community/buildout/src/zc/buildout/buildout.py", line 1524, in initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
  File "/Users/maurits/community/buildout/src/zc/buildout/buildout.py", line 1478, in _install_and_load
    return pkg_resources.load_entry_point(
  File "/Users/maurits/community/buildout/venvs/python3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/maurits/community/buildout/venvs/python3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/Users/maurits/community/buildout/venvs/python3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/Users/maurits/community/buildout/venvs/python3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'mkdir'
```