Debug test failures on Mac.
This includes temporary changes so we only run tests on Mac.
It builds on https://github.com/buildout/buildout/pull/707

See failure on [gh-actions job](https://github.com/buildout/buildout/actions/runs/14742705249/job/41402416038):

```
File "/Users/runner/work/buildout/buildout/doc/getting-started.rst", line 153, in getting-started.rst
Failed example:
    run_buildout(src)
Expected nothing
Got:
    Installing bobo.
    root: Not found: /Users/runner/work/buildout/buildout/src/zc/buildout/testing.pynonexistent/bobo/
    root: Couldn't find index page for 'bobo' (maybe misspelled?)
    root: Scanning index of all packages (this may take a while)
    root: Not found: /Users/runner/work/buildout/buildout/src/zc/buildout/testing.pynonexistent/
    Getting distribution for 'bobo'.
    While:
      Installing bobo.
      Getting distribution for 'bobo'.
    Error: Couldn't find a distribution for 'bobo'.
    <BLANKLINE>
```